#!/bin/sh

codename=rote
version=3.1.0-1

reprepro remove $codename linux
reprepro remove $codename block-modules-$version-generic-di &&
reprepro remove $codename block-modules-$version-generic-pae-di &&
reprepro remove $codename block-modules-$version-virtual-di && 
reprepro remove $codename crypto-modules-$version-generic-di &&
reprepro remove $codename crypto-modules-$version-generic-pae-di &&
reprepro remove $codename crypto-modules-$version-virtual-di &&
reprepro remove $codename fat-modules-$version-generic-di &&
reprepro remove $codename fat-modules-$version-generic-pae-di &&
reprepro remove $codename fat-modules-$version-virtual-di &&
reprepro remove $codename fb-modules-$version-generic-di &&
reprepro remove $codename fb-modules-$version-generic-pae-di &&
reprepro remove $codename fb-modules-$version-virtual-di &&
reprepro remove $codename firewire-core-modules-$version-generic-di &&
reprepro remove $codename firewire-core-modules-$version-generic-pae-di &&
reprepro remove $codename floppy-modules-$version-generic-di &&
reprepro remove $codename floppy-modules-$version-generic-pae-di &&
reprepro remove $codename floppy-modules-$version-virtual-di &&
reprepro remove $codename fs-core-modules-$version-generic-di &&
reprepro remove $codename fs-core-modules-$version-generic-pae-di &&
reprepro remove $codename fs-core-modules-$version-virtual-di &&
reprepro remove $codename fs-secondary-modules-$version-generic-di &&
reprepro remove $codename fs-secondary-modules-$version-generic-pae-di &&
reprepro remove $codename fs-secondary-modules-$version-virtual-di &&
reprepro remove $codename input-modules-$version-generic-di &&
reprepro remove $codename input-modules-$version-generic-pae-di &&
reprepro remove $codename irda-modules-$version-generic-di &&
reprepro remove $codename irda-modules-$version-generic-pae-di &&
reprepro remove $codename irda-modules-$version-virtual-di &&
reprepro remove $codename kernel-image-$version-generic-di &&
reprepro remove $codename kernel-image-$version-generic-pae &&
reprepro remove $codename linux-doc &&
reprepro remove $codename linux-headers-$version-generic-pae &&
reprepro remove $codename linux-headers-$version-generic &&
reprepro remove $codename linux-headers-$version-server &&
reprepro remove $codename linux-headers-$version-virtual &&
reprepro remove $codename linux-headers-$version &&
reprepro remove $codename linux-image-$version-generic-pae &&
reprepro remove $codename linux-image-$version-generic &&
reprepro remove $codename linux-image-$version-server &&
reprepro remove $codename linux-image-$version-virtual &&
reprepro remove $codename linux-image-extra-$version-virtual &&
reprepro remove $codename linux-libc-dev &&
reprepro remove $codename linux-source-3.1.0 &&
reprepro remove $codename linux-tools-3.1 &&
reprepro remove $codename linux-tools-common &&
reprepro remove $codename md-modules-$version-generic-di &&
reprepro remove $codename md-modules-$version-generic-pae-di &&
reprepro remove $codename md-modules-$version-virtual-di &&
reprepro remove $codename message-modules-$version-generic-di &&
reprepro remove $codename message-modules-$version-generic-pae-di &&
reprepro remove $codename message-modules-$version-virtual-di &&
reprepro remove $codename mouse-modules-$version-generic-di &&
reprepro remove $codename mouse-modules-$version-generic-pae-di &&
reprepro remove $codename mouse-modules-$version-virtual-di &&
reprepro remove $codename nfs-modules-$version-generic-di &&
reprepro remove $codename nfs-modules-$version-generic-pae-di &&
reprepro remove $codename nic-modules-$version-generic-di &&
reprepro remove $codename nic-modules-$version- generic-pae-di &&
reprepro remove $codename nic-modules-$version-virtual-di &&
reprepro remove $codename nic-shared-modules-$version-generic-di &&
reprepro remove $codename nic-shared-modules-$version-generic-pae-di &&
reprepro remove $codename nic-shared-modules-$version-virtual-di &&
reprepro remove $codename nic-usb-modules-$version-generic-di &&
reprepro remove $codename nic-usb-modules-$version-generic-pae &&
reprepro remove $codename parport-modules-$version-generic-di &&
reprepro remove $codename parport-modules-$version-generic-pae-di &&
reprepro remove $codename parport-modules-$version-virtual-di &&
reprepro remove $codename pata-modules-$version-generic-di &&
reprepro remove $codename pata-modules-$version-generic-pae-di &&
reprepro remove $codename pcmcia-modules-$version-generic-di &&
reprepro remove $codename pcmcia-modules-$version-generic-pae-di &&
reprepro remove $codename pcmcia-storage-modules-$version-generic-di &&
reprepro remove $codename pcmcia-storage-modules-$version-generic-pae-di &&
reprepro remove $codename plip-modules-$version-generic-di &&
reprepro remove $codename plip-modules-$version-generic-pae-di &&
reprepro remove $codename ppp-modules-$version-generic-di &&
reprepro remove $codename ppp-modules-$version-generic-pae-di &&
reprepro remove $codename ppp-modules-$version-virtual-di &&
reprepro remove $codename sata-modules-$version-generic-di &&
reprepro remove $codename sata-modules-$version-generic-pae-di &&
reprepro remove $codename sata-modules-$version-virtual-di &&
reprepro remove $codename scsi-modules-$version-generic-di &&
reprepro remove $codename scsi-modules-$version-generic-di &&
reprepro remove $codename scsi-modules-$version -virtual-di &&
reprepro remove $codename serial-modules-$version-generic-di &&
reprepro remove $codename serial-modules-$version-generic-pae-di &&
reprepro remove $codename speakup-modules-$version-generic-di &&
reprepro remove $codename speakup-modules-$version-generic-pae-di &&
reprepro remove $codename squashfs-modules-$version-generic-di &&
reprepro remove $codename squashfs-modules-$version-generic-pae-di &&
reprepro remove $codename squashfs-modules-$version-virtual-di &&
reprepro remove $codename storage-core-modules-$version-generic-di &&
reprepro remove $codename storage-core-modules-$version-generic-pae-di &&
reprepro remove $codename storage-core-modules-$version-virtual-di &&
reprepro remove $codename usb-modules-$version-generic-di &&
reprepro remove $codename usb-modules-$version-generic-pae-di &&
reprepro remove $codename virtio-modules-$version-generic-di &&
reprepro remove $codename virtio-modules-$version-generic-pae-di &&
reprepro remove $codename virtio-modules-$version-virtual-di &&
reprepro remove $codename vlan-modules-$version-generic-di &&
reprepro remove $codename vlan-modules-$version-generic-pae-di &&
reprepro remove $codename vlan-modules-$version-virtual-di 
